apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-claim
  namespace: management
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "2G"
  storageClassName: default